### ISSUE TITLE
Firefox (49.0.1) issue with ifame upload plugin

### ISSUE THREAD

**Issue by vsapram** [cmlenz/jquery-iframe-transport#44]
Data is not reaching server. All values are coming as nulls to the server. Jquery version 1.11

**Comment by mobilutz** [comment]
I am having the same problem. Will try to look into it.

**Comment by mkatajah** [comment]
Having same problem with the jquery. Is this bug in Firefox or did they change javascript handling?

@mobilutz  any ideas?

**Comment by mobilutz** [comment]
It looks like the events are not triggered in FF. For example here: https://github.com/cmlenz/jquery-iframe-transport/blob/master/jquery.iframe-transport.js#L198

I will switch to normal file upload for now without the iframe transport.

**Comment by StephaneRob** [comment]
The load event is not triggered with `src="javascript:false;"` but seems to be correctly triggered with `src="about:blank"` on FF 49.

https://github.com/JangoSteve/remotipart/issues/163

**Comment by mobilutz** [comment]
Thanks for the info. I went with triggering my own event on the iframe after append it to the bottom.
It's not good but works in my case.

I will take a look into the `src` thing.

**Comment by MikeTheReader** [comment]
Was hitting the same problem. Removing the src completely also seems to work in Firefox.

**Comment by octopushugs** [comment]
I'm seeing this happening specifically in Firefox 49 and Chrome on Windows 10, but oddly enough, not on Chrome/OSX.

**Comment by rawat22** [comment]
Any quick solution to fix this ?

**Comment by MikeTheReader** [comment]
The fix by @jbyers above takes care of the problem.

**Comment by jbyers** [comment]
I've submitted as a PR: https://github.com/cmlenz/jquery-iframe-transport/pull/46

Note that my commit to the tes fork 10 days ago is incomplete as that fork has one fewer `src="javascript:...` for other reasons. Use the pull request instead.

**Comment by johnstile** [comment]
Looks like firefox addressed this in https://bugzilla.mozilla.org/show_bug.cgi?id=1306472, found in https://www.mozilla.org/en-US/firefox/49.0.2/releasenotes/

**Comment by cmlenz** [comment]
PR #46 merged. Thanks!
